### ISSUE TITLE
这个可以加上tacking吗？

### ISSUE THREAD

**Issue by Kingsely-o** [Li-Qingyun/sam-mmrotate#1]
SAM+MMrotate这个技术感觉特别适合用在无人机视频中车辆轨迹，行人轨迹的提取，想请教下有没有实现的可能。

**Comment by Li-Qingyun** [comment]
@Kingsely-o  感觉速度会挺慢的，这个实现比较 naive，要解决的问题比较多

**Comment by Li-Qingyun** [comment]
@Kingsely-o 他不是一个单纯的感知模型，是需要其他模型做提示的，你们可以从设计提示信息入手，或者从sam本身的结构和原理出发做端到端的东西

**Comment by Kingsely-o** [comment]
确实，当我处理无人机拍摄的视频时，选择4辆车以上速度变得很慢
